cursor #dee3e6
cursor_text_color #bfc8cc

foreground            #dee3e6
# background            #141414
selection_foreground  #1d333b
selection_background  #b3cad4
url_color             #87d1ea

# black
# color8   #585252
# color0   #4c4c4c

# red
color1   #b8545b
color9   #b15b5f

# green
color2   #87d1ea
color10  #87d1ea

# yellowwa
color3   #b1aa63
color11  #beb769

# blue
/* color4  #776dafff */
color4  #87d1ea
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #c49ec4

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
